### ISSUE TITLE
how to create a prefix lists automatically via script

### ISSUE THREAD

**Issue by Zulzig** [k01ek/netbox-bgp#114]
**NetBox version**
v3.3.4

**Describe the bug**
try to create a prefix list via pynetbox or via requests generate a traceback error.
the fields name, decription and family are required.
expected value for the fields is string.
when you post your request you've got the following return
```cmd
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'family': ['"test" is not a valid choice.']}
```

but if you create a prefix list object manually, you don't have this field.  In addition when you get the previously created object, the field family is a empty string.
```cmd
 v=operator.attrgetter('plugins.bgp.prefix-list')(nb).get(**dict(name='test'))
dict(v)
{'id': 6, 'tags': [], 'custom_fields': {}, 'display': 'test', 'created': '2022-11-22T14:11:32.356173Z', 'last_updated': '2022-11-22T14:11:32.356189Z', 'custom_field_data': {}, 'name': 'test', 'description': '', 'family': ''}
```
I don't understand what's the expected value for family.

**To Reproduce**
```cmd
operator.attrgetter('plugins.bgp.prefix-list')(nb).create(dict(name='pl-test',description='pl-test', family='test')) 
```  

**Expected behavior**
```cmd
operator.attrgetter('plugins.bgp.prefix-list')(nb).create(dict(name='pl-test',description='pl-test', family='test')) 
True
```  
Thank for your support.

**Comment by bgianpetro** [comment]
I did a bit of digging on this because I noticed similar behavior when adding route policies via the API: when you add them in the GUI you only need the name, but when you add them using the API you need both the name and the description.  Specific to the prefix list issue, I found there are two problems:

1. The way the API automation interprets the "unique_together" constraint on the model as required.  Since that is the case for the models in this plugin, it's going to make fields like "description" a requirement when using the API.  I'm not sure this is the desired behavior or method for ensuring uniqueness, but that would be a question for the author.  Personally I think if, for example, we would want a route policy or prefix list to be unique, that could be on something like a device basis, not a combination of name and description.
2. Specific to the prefix list model, the choices for Address Family are integers instead of strings.  So even if you want to add a prefix list via the API you can't because there are no valid choices for Address Family.  I've submitted Pull Request #123 to address this so at the minimum you could set an Address Family as part of the API creation in order to accomplish the goal of automating prefix lists.
